const availableCountries = [
    {country: 'Anguilla', countryCode: 'AI'},
    {country: 'Antigua and Barbuda', countryCode: 'AG'},
    {country: 'Argentina', countryCode: 'AR'},
    {country: 'Armenia', countryCode: 'AM'},
    {country: 'Australia', countryCode: 'AU'},
    {country: 'Austria', countryCode: 'AT'},
    {country: 'Bahamas', countryCode: 'BS'},
    {country: 'Bahrain', countryCode: 'BH'},
    {country: 'Barbados', countryCode: 'BB'},
    {country: 'Belgium', countryCode: 'BE'},
    {country: 'Belize', countryCode: 'BZ'},
    {country: 'Bermuda', countryCode: 'BM'},
    {country: 'Bolivia', countryCode: 'BO'},
    {country: 'Botswana', countryCode: 'BW'},
    {country: 'Brazil', countryCode: 'BR'},
    {country: 'Bulgaria', countryCode: 'BG'},
    {country: 'Cameroon', countryCode: 'CM'},
    {country: 'Canada', countryCode: 'CA'},
    {country: 'Cayman Islands', countryCode: 'CYM'},
    {country: 'Central African Republic', countryCode: 'CF'},
    {country: 'Chile', countryCode: 'CL'},
    {country: 'China', countryCode: 'CN'},
    {country: 'Colombia', countryCode: 'CO'},
    {country: 'Costa Rica', countryCode: 'CR'},
    {country: "Cote D'Ivoire", countryCode: 'CI'},
    {country: 'Croatia', countryCode: 'HR'},
    {country: 'Czech Republic', countryCode: 'CZ'},
    {country: 'Denmark', countryCode: 'DK'},
    {country: 'Dominica', countryCode: 'DM'},
    {country: 'Dominican Republic', countryCode: 'DO'},
    {country: 'Ecuador', countryCode: 'EC'},
    {country: 'Egypt', countryCode: 'EG'},
    {country: 'El Salvador', countryCode: 'SV'},
    {country: 'Equatorial Guinea', countryCode: 'GQ'},
    {country: 'Estonia', countryCode: 'EE'},
    {country: 'Finland', countryCode: 'FI'},
    {country: 'France', countryCode: 'FR'},
    {country: 'Germany', countryCode: 'DE'},
    {country: 'Greece', countryCode: 'GR'},
    {country: 'Grenada', countryCode: 'GD'},
    {country: 'Guatemala', countryCode: 'GT'},
    {country: 'Guinea', countryCode: 'GN'},
    {country: 'Guinea-Bissau', countryCode: 'GW'},
    {country: 'Guyana', countryCode: 'GY'},
    {country: 'Honduras', countryCode: 'HN'},
    {country: 'Hong Kong', countryCode: 'HK'},
    {country: 'Hungary', countryCode: 'HU'},
    {country: 'India', countryCode: 'IN'},
    {country: 'Indonesia', countryCode: 'ID'},
    {country: 'Ireland', countryCode: 'IE'},
    {country: 'Israel', countryCode: 'IL'},
    {country: 'Italy', countryCode: 'IT'},
    {country: 'Jamaica', countryCode: 'JM'},
    {country: 'Japan', countryCode: 'JP'},
    {country: 'Jordan', countryCode: 'JO'},
    {country: 'Kenya', countryCode: 'KE'},
    {country: 'Korea', countryCode: 'KOR'},
    {country: 'Kuwait', countryCode: 'KW'},
    {country: 'Latvia', countryCode: 'LV'},
    {country: 'Liechtenstein', countryCode: 'LI'},
    {country: 'Lithuania', countryCode: 'LT'},
    {country: 'Luxembourg', countryCode: 'LU'},
    {country: 'Macao', countryCode: 'MO'},
    {country: 'Macedonia, The Former Yugoslav Republic of', countryCode: 'MK'},
    {country: 'Madagascar', countryCode: 'MG'},
    {country: 'Malaysia', countryCode: 'MY'},
    {country: 'Mali', countryCode: 'ML'},
    {country: 'Malta', countryCode: 'MT'},
    {country: 'Mauritius', countryCode: 'MU'},
    {country: 'Mexico', countryCode: 'MX'},
    {country: 'Moldova, Republic of', countryCode: 'MD'},
    {country: 'Montenegro', countryCode: 'MNE'},
    {country: 'Montserrat', countryCode: 'MS'},
    {country: 'Morocco', countryCode: 'MA'},
    {country: 'Mozambique', countryCode: 'MZ'},
    {country: 'Netherlands', countryCode: 'NL'},
    {country: 'New Zealand', countryCode: 'NZ'},
    {country: 'Nicaragua', countryCode: 'NI'},
    {country: 'Niger', countryCode: 'NE'},
    {country: 'Nigeria', countryCode: 'NG'},
    {country: 'Norway', countryCode: 'NO'},
    {country: 'Oman', countryCode: 'OM'},
    {country: 'Panama', countryCode: 'PA'},
    {country: 'Paraguay', countryCode: 'PY'},
    {country: 'Peru', countryCode: 'PE'},
    {country: 'Philippines', countryCode: 'PH'},
    {country: 'Poland', countryCode: 'PL'},
    {country: 'Portugal', countryCode: 'PT'},
    {country: 'Puerto Rico', countryCode: 'PR'},
    {country: 'Qatar', countryCode: 'QAT'},
    {country: 'Romania', countryCode: 'RO'},
    {country: 'Russian Federation', countryCode: 'RU'},
    {country: 'Saudi Arabia', countryCode: 'SAU'},
    {country: 'Senegal', countryCode: 'SEN'},
    {country: 'Singapore', countryCode: 'SG'},
    {country: 'Slovakia', countryCode: 'SK'},
    {country: 'Slovenia', countryCode: 'SI'},
    {country: 'South Africa', countryCode: 'ZA'},
    {country: 'Spain', countryCode: 'ES'},
    {country: 'St. Kitts & Nevis', countryCode: 'KNA'},
    {country: 'St. Lucia', countryCode: 'LCA'},
    {country: 'St. Vincent & The Grenadines', countryCode: 'VCT'},
    {country: 'Suriname', countryCode: 'SR'},
    {country: 'Sweden', countryCode: 'SE'},
    {country: 'Switzerland', countryCode: 'CH'},
    {country: 'Taiwan, Province of China', countryCode: 'TW'},
    {country: 'Thailand', countryCode: 'TH'},
    {country: 'Trinidad and Tobago', countryCode: 'TT'},
    {country: 'Tunisia', countryCode: 'TN'},
    {country: 'Turkey', countryCode: 'TR'},
    {country: 'Turks and Caicos Islands', countryCode: 'TCA'},
    {country: 'Uganda', countryCode: 'UG'},
    {country: 'United Arab Emirates', countryCode: 'AE'},
    {country: 'United Kingdom', countryCode: 'GB'},
    {country: 'United States', countryCode: 'US'},
    {country: 'Uruguay', countryCode: 'UY'},
    {country: 'Venezuela', countryCode: 'VE'},
    {country: 'Viet Nam', countryCode: 'VN'},
    {country: 'Virgin Islands, British', countryCode: 'VG'}
];

export default availableCountries;
